### ISSUE TITLE
Enable travis builds for aspell-fuzz

### ISSUE THREAD

**Issue by cmeister2** [GNUAspell/aspell-fuzz#2]
There's a Travis CI script that is currently not being run because I don't have enough permissions to enable Travis CI for this repository. It'd be nice to get some regressible testing inside the OSS-Fuzz container for any future changes that get made.

**Comment by kevina** [comment]
I don't see a `.travis.yml` file.  Did you forget to commit that?

**Comment by cmeister2** [comment]
Nope - I was going to add one when travis was enabled.

**Comment by kevina** [comment]
It should be enabled for travis-ci.org.  Please create a p.r.

**Comment by cmeister2** [comment]
Will do.
